config/routes.rb
Rails.application.routes.draw do
  devise_for :employees, path: "employees",controllers: {
        registrations: 'employees/registrations'
      }
  resources :employees
  resources :leave_requests do
    post :approve, on: :member
    post :reject, on: :member
  end
  resources :projects do
    post :assign_employee, on: :member
    # resources :employee_project
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'employees#index'
end

app/models/leave_request.rb
class LeaveRequest < ApplicationRecord
  belongs_to :employee
  validates  :start_date,:end_date, :reason, presence:true
end

app/controllers/leave_requests_controller.rb
class LeaveRequestsController < ApplicationController
  before_action :set_leaverequest, only: [:approve, :reject]

 def index
  if current_employee.has_role? :admin
    @leave_request = LeaveRequest.all
  else
    @leave_request = LeaveRequest.where(employee_id: current_employee.id)
  end
 end

  def new
   @leave_request = LeaveRequest.new
  end

    
  def create
    @leave_request = LeaveRequest.new(leave_params)
    @leave_request.employee_id = current_employee.id

    respond_to do |format|
      if @leave_request.save
        format.html { redirect_to leave_requests_path, notice: 'Leave request successfully created.' }
        # format.json { render :show, status: :created, location: @leave_request }
      else
        format.html { render :new }
        format.json { render json: @leave_request.errors, status: :unprocessable_entity }
      end
    end
  end

  def approve
      @leave_request.update(approve: true)
      redirect_to leave_requests_path, notice: 'Leave approved' 
  end

  def reject
      @leave_request.update(reject: true)
      redirect_to leave_requests_path, notice: 'Leave rejected' 
  end

   
  private

  def set_leaverequest
    @leave_request = LeaveRequest.find(params[:id])
  end

  def leave_params
    params.require(:leave_request).permit(:start_date, :end_date, :reason, :employee_id, 
    :approve, :reject)
  end
  
end

app/helpers/leave_requests_helper.rb
module LeaveRequestsHelper
end

app/views/leave_requests/_form.html.erb
<%= simple_form_for(@leave_request) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
<div class="container">
  <div class="form-inputs">
    <%= f.input :start_date, :as => :string %>
    <%= f.input :end_date, :as => :string %>
    <%= f.input :reason%>
  </div>
 
  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-outline-success"%>  
  </div>
  
</div>

<% end %>
<script type="text/javascript">
  $( "#leave_request_start_date" ).datepicker({
    changeMonth: true,
    changeYear: true,
    yearRange:'2019:2020',
    dateFormat: 'yy-mm-dd'
  });
  $( "#leave_request_end_date" ).datepicker({
    changeMonth: true,
    changeYear: true,
    yearRange:'2019:2030',
    dateFormat: 'yy-mm-dd'
  });
</script>

app/views/leave_requests/index.html.erb
<div class="container">

  <table class="table">
    <thead class="thead-dark">
      <tr>
        <% if current_employee.has_role? :admin %>
        <th scope="col">Name</th>
        <% end %>
        <th scope="col">Start Date</th>
        <th scope="col">End Date</th>
        <th scope="col">Reason</th>
        <th colspan="1" "></th>
      </tr>
    </thead>
      <tbody>
        <% @leave_request.each do |leave_request| %>
        <tr>
         <% if current_employee.has_role? :admin %>
            <td><%= leave_request.employee.firstname %>
         <% end %>
         <td><%= leave_request.start_date %></td>
         <td><%= leave_request.end_date %></td>
         <td><%= leave_request.reason %></td>

         <% if current_employee.has_role? :admin %> 
            <% if !leave_request.approve && !leave_request.reject %>
               <td><%= link_to 'Approve', approve_leave_request_path(leave_request),
                method: :post, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-dark" %>
                  <%= link_to 'Reject', reject_leave_request_path(leave_request),
                method: :post, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-dark"%>
               </td>
            <% elsif leave_request.approve %>
               <td><font color="green">Approved</font></td>
            <% elsif leave_request.reject %>
               <td><font color="red">Rejected</font></td>
            <% end %>
         <% else %>
             <% if leave_request.approve %>
                <td><font color="green">Approved</font></td>
             <% end %>
             <% if leave_request.reject %>
                <td><font color="red">Rejected</font></td>
             <% end %>
        <% end %>
         
      </tr>
        <% end %>
      </tbody>
   </table>
  
  <% if !current_employee.has_role? :admin %> 
  <%= link_to 'New ', new_leave_request_path , class:"btn btn-outline-dark" %>
  <% end %>

</div>
      

app/views/leave_requests/new.html.erb
<h1>New</h1>

<%= render 'form', leave_request: @leave_request %>