config/routes.rb
Rails.application.routes.draw do
  devise_for :employees, path: "employees",controllers: {
        registrations: 'employees/registrations'
      }
  resources :employees
  resources :leave_requests do
    post :approve, on: :member
    post :reject, on: :member
  end
  resources :projects do
    post :assign_employee, on: :member
    # resources :employee_project
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'employees#index'
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :employee_projects
  has_many :employees, through: :employee_projects
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @project = Project.all
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    respond_to do |format|
      if @project.save
        format.html { redirect_to projects_path, notice: 'New project successfully created.' }
        # format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @project = Project.find(params[:id])
  end

  def assign_employee
    # @employee_project= EmployeeProject.new(assign_params)
    # respond_to do |format|
    #   if @employee_project.save

    #     format.html { redirect_to project_path, notice: 'Assigned employees.' }
    #     format.json { render :show, status: :created, location: @project }
    #   else

    #     format.html { redirect_to project_path, alert: @employee_project.errors  }
    #     format.json { render json: @employee_project.errors, status: :unprocessable_entity }
    #   end
    # end
    # binding.pry
    arr = params[:employee_id]
    arr.each do |a|
      EmployeeProject.create(employee_id: a, project_id: params[:id])
    end
    redirect_to project_path
  end

  private
    
    def project_params
      params.require(:project).permit(:name, :details)
    end
    
    def assign_params
      params.permit(:employee_id, :project_id)
    end


end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= simple_form_for(@project) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="container">
    <div class="form-inputs">
      <%= f.input :name %>
      <%= f.input :details %>
    </div>
   
    <div class="form-actions">
      <%= f.button :submit, class: "btn btn-outline-success"%>  
    </div>
    
  </div>
<% end %>

app/views/projects/index.html.erb
<div class="container">
  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Details</th>
      </tr>
    </thead>
    <tbody>
      <% @project.each do |project| %>
        <tr>
          <td><%= project.name %></td>
          <td><%= project.details %></td>
          <td><%= link_to 'show',project_path(project) %>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%# if !current_employee.has_role? :admin %> 
  <%= link_to 'New ', new_project_path , class:"btn btn-outline-dark" %>
  <%# end %>
</div>

app/views/projects/new.html.erb
<h1>New</h1>

<%= render 'form', projects: @project %>

app/views/projects/show.html.erb
<div class="container">
    <%#= f.collection_select(:employee_id, Employee.all, :id, :name, {:prompt => "Please Select a employee"}, {:multiple => true}) %>
    <%#= collection_select(:employee, :employee_id, Employee.all, :id, :first_name) %>
    <%= form_tag(assign_employee_project_path(@project), method: :post) do %>
      <%= select_tag "employee_id", options_from_collection_for_select(Employee.all, "id", "firstname"), multiple: true,prompt:"select employee",style: "width: 200px;" %>
      <%= submit_tag %>
    <% end %>
</div>