config/routes.rb
Rails.application.routes.draw do
  devise_for :employees, path: "employees",controllers: {
        registrations: 'employees/registrations'
      }
  resources :employees
  resources :leave_requests do
    post :approve, on: :member
    post :reject, on: :member
  end
  resources :projects do
    post :assign_employee, on: :member
    # resources :employee_project
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'employees#index'
end

app/views/layouts/_header.html.erb
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
  <h3 style="color:#404040" class="my-0 mr-md-auto font-weight-normal">Employee Management</h3>

  <% if employee_signed_in? %>
    <nav class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <%= current_employee.email %>
      </a>
      <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <% if current_employee.has_role? :admin %>
            <%= link_to 'Home', employees_path  , class: 'dropdown-item' %>
            <%= link_to 'New Employee',new_employee_registration_path, class: 'dropdown-item' %>
            <%= link_to 'Edit profile', edit_employee_path(current_employee), class: 'dropdown-item' %>
        <% else %>
            <%= link_to 'Home', employee_path(current_employee)  , class: 'dropdown-item' %>
        <% end %>
        <%= link_to 'Projects', projects_path , class: 'dropdown-item' %>
        <%= link_to 'Leave Request', leave_requests_path  , class: 'dropdown-item' %>
        <%= link_to "Logout", destroy_employee_session_path, method: :delete, class: 'dropdown-item' %>
      </div>
    </nav>
  <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EmployeeManagement</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <% if notice %>
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        <%= notice %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>

    <% if alert %>
      <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <%= alert %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
   
    <%= yield %>
  </body>
</html>